// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/aladinbank/aladinbank.proto

package aladinbank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AladinBankService_TransferFunds_FullMethodName = "/aladinbank.AladinBankService/TransferFunds"
	AladinBankService_GetBalance_FullMethodName    = "/aladinbank.AladinBankService/GetBalance"
)

// AladinBankServiceClient is the client API for AladinBankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AladinBankServiceClient interface {
	TransferFunds(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
}

type aladinBankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAladinBankServiceClient(cc grpc.ClientConnInterface) AladinBankServiceClient {
	return &aladinBankServiceClient{cc}
}

func (c *aladinBankServiceClient) TransferFunds(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, AladinBankService_TransferFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aladinBankServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, AladinBankService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AladinBankServiceServer is the server API for AladinBankService service.
// All implementations must embed UnimplementedAladinBankServiceServer
// for forward compatibility.
type AladinBankServiceServer interface {
	TransferFunds(context.Context, *TransferRequest) (*TransferResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	mustEmbedUnimplementedAladinBankServiceServer()
}

// UnimplementedAladinBankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAladinBankServiceServer struct{}

func (UnimplementedAladinBankServiceServer) TransferFunds(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFunds not implemented")
}
func (UnimplementedAladinBankServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedAladinBankServiceServer) mustEmbedUnimplementedAladinBankServiceServer() {}
func (UnimplementedAladinBankServiceServer) testEmbeddedByValue()                           {}

// UnsafeAladinBankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AladinBankServiceServer will
// result in compilation errors.
type UnsafeAladinBankServiceServer interface {
	mustEmbedUnimplementedAladinBankServiceServer()
}

func RegisterAladinBankServiceServer(s grpc.ServiceRegistrar, srv AladinBankServiceServer) {
	// If the following call pancis, it indicates UnimplementedAladinBankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AladinBankService_ServiceDesc, srv)
}

func _AladinBankService_TransferFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AladinBankServiceServer).TransferFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AladinBankService_TransferFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AladinBankServiceServer).TransferFunds(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AladinBankService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AladinBankServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AladinBankService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AladinBankServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AladinBankService_ServiceDesc is the grpc.ServiceDesc for AladinBankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AladinBankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aladinbank.AladinBankService",
	HandlerType: (*AladinBankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferFunds",
			Handler:    _AladinBankService_TransferFunds_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _AladinBankService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/aladinbank/aladinbank.proto",
}
